version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4000:4000
    volumes:
      - ./frontend:/frontend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./backend:/backend
    env_file: .env
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres/:/var/lib/postgresql/data
    env_file: .env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  nginx:
    image: nginx:1.24.0-alpine
    restart: always
    volumes:
      - ./nginx/conf/bytehub.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - 80:80
    depends_on:
      - postgres
      - backend
      - frontend
