version: "3"

services:
  frontend:
    build: ./frontend
    ports:
      - 4000:4000
    env_file: .env

  backend:
    build: ./backend
    ports:
      - 3000:3000
    env_file: .env

  postgres:
    image: postgres:15.3
    ports:
      - 5432:5432
    volumes:
      - ./postgres/:/var/lib/postgresql/data
    env_file: .env

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf/bytehub.conf:/etc/nginx/nginx.conf
      - ./frontend/dict:/usr/share/nginx/html
    ports:
      - 80:80
