version: "3"

services:
  frontend:
    build: ./frontend

  backend:
    build: ./backend
    ports:
      - 3000:3000
    env_file: .env
    depends_on:
      - postgres

  postgres:
    image: postgres:15.3
    ports:
      - 5432:5432
    volumes:
      - ./postgres/:/var/lib/postgresql/data
    env_file: .env

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf/bytehub.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - 80:80
    depends_on:
      - postgres
      - backend
      - frontend
