version: "3"

services:
  frontend:
    build: ./frontend

  backend:
    build: ./backend
    restart: always
    env_file: .env
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    restart: always
    volumes:
      - ./postgres/:/var/lib/postgresql/data
    env_file: .env

  adminer:
    image: adminer
    restart: always
    ports:
      - 9642:8080

  nginx:
    image: nginx:1.24.0-alpine
    restart: always
    volumes:
      - ./nginx/conf/bytehub.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - 80:80
    depends_on:
      - postgres
      - backend
      - frontend
